name: indian_tv_streaming
description: A premium mobile streaming platform for Indian television content

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.9.2

  # Backend & API
  supabase_flutter: ^2.0.0
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Video Player
  video_player: ^2.8.1
  better_player: ^0.0.84
  chewie: ^1.7.5

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Notifications
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.0

  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.1.0
  path: ^1.8.3

  # Networking & Connectivity
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  crypto: ^3.0.3
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

  # UI Components
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_slidable: ^3.0.1

  # Animation & Effects
  rive: ^0.12.4
  flutter_animate: ^4.3.0

  # Development
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700

